apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Baremetal-deploy-from-Ansible
  title: Deploy application from Ansible
  description: Baremetal deployment of application from Ansible
spec:
  owner: user:guest
  type: service

  
  parameters:
    - title: GitHub Repository URL
      required: 
        - Github_URL
        #- Dockerfile
        #- Port
      properties:
        Github_URL:
          title: Enter you Github URL
          type: string
          description: Enter the github URL where your code exists
          ui:autofocus: true

    - title: Select where you want to deploy your code
      required:
        - stack
      properties:
        stack:
          title: Select from below list
          type: string
          enum:
            - Docker
            - Github pages
            - Baremetal
            - Kubernetes
  
    - title: Enter below details
      dependencies:
        stack:
          oneOf:
            - properties:
                stack:
                  const: Baremetal
                extraFields:          # 👈 wrap everything else inside a schema key
                  title: Enter the details
                  type: object
                  properties:
                    PlaybookPath:
                      title: Enter the Path of dockercompose
                      type: string
                      description: Enter the PlaybookPath
                      default: "docker-compose.yml" 
  
            - properties:
                stack:
                  const: Github pages
                extraFields:
                  type: object
                  properties: {}
  
            - properties:
                stack:
                  const: Kubernetes
                extraFields:
                  type: object
                  properties: {}
  
            - properties:
                stack:
                  const: Docker
                extraFields:
                  type: object
                  properties: {}
            

          
  steps:
    # - id: fetch-template
    #   name: Fetch template files
    #   action: fetch:plain
    #   input:
    #     url: ${{ parameters.Github_URL }}
    #     targetPath: .
        
    - id: fetch-repo
      name: Fetch GitHub Repository Archive
      action: fetch:plain
      input:
        url: ./Cafe_Dynamic_Website-main
        targetPath: repo.zip
  
    # Step 2: Unzip the repo
    - id: unzip-repo
      name: Unzip Repository
      action: shell:run
      input:
        command: unzip
        args: ["repo.zip", "-d", "."]
  
    # Step 3: Run Docker Compose
    - id: run-docker-compose
      name: Run Docker Compose
      if: ${{ parameters.stack == 'Baremetal' }}
      action: shell:run
      input:
        cwd: ./$(basename ${{ parameters.Github_URL | replace('.git','') }})-main
        command: docker
        args: ["compose", "up", "--build"]


    # - id: unzip-repo
    #   name: Unzip Repository
    #   action: shell:run
    #   input:
    #     command: unzip
    #     args: ["repo.zip", "-d", "."]

    # # Step 3: Deploy containers via Docker Compose
    # - id: docker-compose-up
    #   name: Deploy Containers via Docker Compose
    #   action: shell:run
    #   input:
    #     cwd: ./$(basename ${{ parameters.Github_URL | replace('.git','') }})-main
    #     command: bash
    #     args:
    #       - -c
    #       - |
    #         set -e
    #         echo "Deploying application using Docker Compose..."
            
    #         if [ -f "${{ parameters.ComposeFile }}" ]; then
    #           echo "Stopping any existing containers..."
    #           docker-compose -f "${{ parameters.ComposeFile }}" down || true
              
    #           echo "Starting containers..."
    #           docker-compose -f "${{ parameters.ComposeFile }}" up -d
              
    #           echo "Containers started successfully!"
    #         else
    #           echo "Error: docker-compose.yml not found at '${{ parameters.ComposeFile }}'"
    #           exit 1
    #         fi

