apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Baremetal-deploy-from-Ansible
  title: Deploy application from Ansible
  description: Baremetal deployment of application from Ansible
spec:
  owner: user:guest
  type: service

  
  parameters:
    - title: GitHub Repository URL
      required: 
        - Github_URL
        #- Dockerfile
        #- Port
      properties:
        Github_URL:
          title: Enter you Github URL
          type: string
          description: Enter the github URL where your code exists
          ui:autofocus: true

    - title: Select where you want to deploy your code
      required:
        - stack
      properties:
        stack:
          title: Select from below list
          type: string
          enum:
            - Docker
            - Github pages
            - Baremetal
            - Kubernetes
  
    - title: Enter below details
      dependencies:
        stack:
          oneOf:
            - properties:
                stack:
                  const: Baremetal
                extraFields:          # 👈 wrap everything else inside a schema key
                  title: Enter the details
                  type: object
                  properties:
                    PlaybookPath:
                      title: Enter the Path of dockercompose
                      type: string
                      description: Enter the PlaybookPath
                      default: "docker-compose.yml" 
  
            - properties:
                stack:
                  const: Github pages
                extraFields:
                  type: object
                  properties: {}
  
            - properties:
                stack:
                  const: Kubernetes
                extraFields:
                  type: object
                  properties: {}
  
            - properties:
                stack:
                  const: Docker
                extraFields:
                  type: object
                  properties: {}
            

          
  steps:
    - id: Run Playbook
      name: Run Playbook
      if: ${{ parameters.stack == 'Baremetal' }}
      action: shell:run
      input:
        command: sudo
        args: ["docker-compose", "up", "--build"]
